name: SaludYa CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Allow specific builds
        run: pnpm approve-builds bcrypt core-js core-js-pure

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar pruebas
        run: CI=true pnpm test -- --watchAll=false

      - name: Compilar aplicación
        run: pnpm build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Verificar sintaxis
        run: node --check server.js