name: SaludYa CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Activar Corepack
        run: corepack enable

      - name: Activar pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Permitir builds de dependencias nativas
        run: pnpm approve-builds --all

      - name: Instalar dependencias
        run: pnpm install


  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Activar Corepack
        run: corepack enable

      - name: Activar pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Permitir builds de dependencias nativas
        run: pnpm approve-builds --all

      - name: Instalar dependencias
        run: pnpm install

      - name: Verificar backend
        run: node --check server.js