name: SaludYa CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build frontend
        run: pnpm run build


  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check backend
        run: node server.js --check


  deploy:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy
        run: echo "Deploy a Vercel / Render aquí"